on:
  push:
    branches:
      - reference/*
      - lecture/*
jobs:
  build:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --fail-at-end
      - name: Publish Test Report
        run: scacap/action-surefire-report@v1

          